name: Build Resume

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
  # Allows workflow to be called elsewhere in actions
  workflow_call:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - name: Download gist
        env:
          GH_TOKEN: ${{ secrets.GH_GIST_PAT }}
        run: gh gist view 1d37721f321070f6018947bfc4a8e9a5 -r | tee resume.json

      - name: Install resume build
        run: npm install -g resumed jsonresume-theme-kendall

      - name: Build resume
        run: |
          resumed --theme jsonresume-theme-kendall

      - uses: actions/upload-artifact@v4
        name: Save HTML
        with:
          name: resume.html
          path: resume.html

    


    

